repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.14'
    hooks:
      - id: ruff
        files: "^datamodel_code_generator|^tests"
        exclude: "^tests/data"
        args: [ --fix ]
      - id: ruff-format
        files: "^datamodel_code_generator|^tests"
        exclude: "^tests/data"
