repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.8.4'
  hooks:
  - id: ruff
    files: "^datamodel_code_generator|^tests"
    exclude: "^tests/data"
    args: [ --fix ]
  - id: ruff-format
    files: "^datamodel_code_generator|^tests"
    exclude: "^tests/data"
- repo: https://github.com/codespell-project/codespell
  # Configuration for codespell is in pyproject.toml
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
    exclude: "^tests/|^CODE_OF_CONDUCT.md"
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
  - id: poetry-check