repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.0'
    hooks:
      - id: ruff
        files: "^datamodel_code_generator|^tests"
        exclude: "^tests/data"
        args: [ --fix ]
      - id: ruff-format
        files: "^datamodel_code_generator|^tests"
        exclude: "^tests/data"
  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in pyproject.toml
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
      exclude: "^tests/|^CODE_OF_CONDUCT.md"
