ci:
  skip: [readme]

repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.35.0
  hooks:
    - id: check-github-workflows
      args: [ "--verbose" ]
- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: "1.7.0"
  hooks:
    - id: tox-ini-fmt
      args: ["-p", "fix"]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.11.1
  hooks:
    - id: pyproject-fmt
      args: ["--max-supported-python=3.14"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.14.7'
  hooks:
  - id: ruff-format
    exclude: "^tests/data"
  - id: ruff
    exclude: "^tests/data"
    args: ["--fix", "--unsafe-fixes", "--exit-non-zero-on-fix"]
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
    exclude: "^tests/|^CODE_OF_CONDUCT.md"
- repo: local
  hooks:
  - id: readme
    name: Update README command help
    entry: bash -c 'test -x .tox/fix/bin/python || tox run -e fix --notest -qq; .tox/fix/bin/python scripts/update_command_help_on_markdown.py'
    language: system
    files: ^(src/datamodel_code_generator/arguments\.py|README\.md|docs/index\.md)$
    pass_filenames: false
