repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: "^datamodel_code_generator|^tests"
        exclude: "^tests/data"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.286'
    hooks:
      - id: ruff
        files: "^datamodel_code_generator|^tests"
        exclude: "^tests/data"
        args: [--fix, --exit-non-zero-on-fix]
