site_name: datamodel-code-generator
site_description: This code generator creates pydantic model from an openapi file and others.

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'

markdown_extensions:
  - codehilite
  - admonition

repo_name: koxudaxi/datamodel-code-generator
repo_url: https://github.com/koxudaxi/datamodel-code-generator

google_analytics:
    - 'UA-142130505-1'
    - 'auto'

nav:
    - Overview: index.md
    - Support data types: support-data-types.md
    - Usage:
      - Generate from OpenAPI: openapi.md
      - Generate from JSON Schema: jsonschema.md
      - Generate from JSON Data: jsondata.md
      - Using as module: using_as_module.md
      - Formatting: formatting.md
      - Field Constraints: field-constraints.md
      - pyproject.toml: pyproject_toml.md
    - Development-Contributing: development-contributing.md

plugins:
  - search