name: Check config types

on:
  push:
    paths:
      - 'src/datamodel_code_generator/config.py'
      - 'src/datamodel_code_generator/_types/**'
      - 'pyproject.toml'
      - '.github/workflows/config-types.yaml'
  pull_request:
    paths:
      - 'src/datamodel_code_generator/config.py'
      - 'src/datamodel_code_generator/_types/**'
      - 'pyproject.toml'
      - '.github/workflows/config-types.yaml'

jobs:
  config-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          profile: generate-config-dict

      - uses: ./
        with:
          profile: parser-config-dicts

      - uses: ./
        with:
          profile: parse-config-dict
