name: Update README

on:
  push:
    branches: [main]
    paths:
      - 'src/datamodel_code_generator/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/datamodel_code_generator/**'

permissions:
  contents: write

jobs:
  update-readme:
    if: github.event_name == 'push' || !github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}
          token: ${{ secrets.PAT }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv
      - name: Setup environment
        run: tox run -vv --notest --skip-missing-interpreters false -e readme
        env:
          UV_PYTHON_PREFERENCE: "only-managed"
      - name: Update README
        run: .tox/readme/bin/python scripts/update_command_help_on_markdown.py
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md docs/index.md
          git diff --staged --quiet || git commit -m "docs: update command help in README

          ðŸ¤– Generated by GitHub Actions"
          git push
